const menuList = [
  {
    name: "j' mugs lasagna",
    price: "60.00",
    category: "main",
    src: "../img/menu/lasagna.jpg",
  },
  {
    name: "barbeque",
    price: "20.00",
    category: "main",
    src: "../img/menu/barbeque.jpg",
  },
  {
    name: "chicken alfredo",
    price: "60.00",
    category: "main",
    src: "../img/menu/chicken-alfredo.jpg",
  },
  {
    name: "chicken nuggets with fries",
    price: "70.00",
    category: "main",
    src: "../img/menu/chicken-nuggets-with-fries.jpg",
  },
  {
    name: "cookies",
    price: "10.00",
    category: "main",
    src: "../img/menu/cookies.jpg",
  },
  {
    name: "fruit shake",
    price: "60.00",
    category: "beverage",
    src: "../img/menu/fruit-shake.jpg",
  },
  {
    name: "strawberry milkshake",
    price: "60.00",
    category: "beverage",
    src: "../img/menu/strawberry-milkshake.jpg",
  },
  {
    name: "choco milkshake",
    price: "60.00",
    category: "beverage",
    src: "../img/menu/choco-milkshake.jpg",
  },
  {
    name: "nutella shake",
    price: "90.00",
    category: "beverage",
    src: "../img/menu/nutella-shake.jpg",
  },
  {
    name: "milktea",
    price: "60.00",
    category: "beverage",
    src: "../img/menu/milktea.jpg",
  },
  {
    name: "regular overload pizza",
    price: "175.00",
    category: "pizza",
    src: "../img/menu/overload.jpg",
  },
  {
    name: "large overload pizza",
    price: "190.00",
    category: "pizza",
    src: "../img/menu/overload.jpg",
  },
  {
    name: "regular supreme pizza",
    price: "170.00",
    category: "pizza",
    src: "../img/menu/supreme.jpg",
  },
  {
    name: "large supreme pizza",
    price: "185.00",
    category: "pizza",
    src: "../img/menu/supreme.jpg",
  },
  {
    name: "regular pepperoni pizza",
    price: "170.00",
    category: "pizza",
    src: "../img/menu/pepperoni.jpg",
  },
  {
    name: "large pepperoni pizza",
    price: "185.00",
    category: "pizza",
    src: "../img/menu/pepperoni.jpg",
  },
  {
    name: "regular hawaiian pizza",
    price: "150.00",
    category: "pizza",
    src: "../img/menu/hawaiian.jpg",
  },
  {
    name: "large hawaiian pizza",
    price: "165.00",
    category: "pizza",
    src: "../img/menu/hawaiian.jpg",
  },
];
